[package]
name = "client"
version = "0.1.0"
authors = ["stillinbeta <web@stillinbeta.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]


[dependencies]
pg-extend = { git = "https://github.com/bluejekyll/pg-extend-rs", rev = "1209b54c17d49ea76c939f171a07a5f9db07b0dc" }

[build-dependencies]
protoc-rust-grpc = "0.6.1"